openapi: "3.0.0"
info:
  title: "Search API"
  version: "1.0.0"
paths:
  "/v1/gifs/search{term}":
    get:
      summary: "Get "
      operationId: "searchByTerm"
      tags:
        - Search
      parameters:
        - name: term
          in: path
          required: true
          description: The term to search for
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
components:
  schemas:
    Data:
      type: object
      items:
        $ref: "#/components/schemas/SearchData"
    SearchData:
      properties:
        title:
          type: string
        url:
          type: string
